### ISSUE TITLE
ValueError: Input object has no element: HtmlProcessingInstruction

### ISSUE THREAD

**Issue by yprez** [codelucas/newspaper#143]
For certain articles the exception `ValueError: Input object has no element: HtmlProcessingInstruction` is raised.

For example, for:

    from newspaper import Article
    article = Article(url='http://www.bostonglobe.com/news/world/2015/05/13/obama-discusses-iran-with-saudi-leaders/YQVleMtSURxsYgxUOznzFO/story.html')
    article.download()
    article.parse()

The traceback:

    /.../local/lib/python2.7/site-packages/newspaper/article.pyc in parse(self)
        221 
        222             text, article_html = output_formatter.get_formatted(
    --> 223                 self.top_node)
        224             self.set_article_html(article_html)
        225             self.set_text(text)

    /.../local/lib/python2.7/site-packages/newspaper/outputformatters.pyc in get_formatted(self, top_node)
         54         self.remove_trailing_media_div()
         55 
    ---> 56         text = self.convert_to_text()
         57         # print(self.parser.nodeToString(self.get_top_node()))
         58         return (text, html)

    /.../local/lib/python2.7/site-packages/newspaper/outputformatters.pyc in convert_to_text(self)
         61         txts = []
         62         for node in list(self.get_top_node()):
    ---> 63             txt = self.parser.getText(node)
         64             if txt:
         65                 txt = HTMLParser().unescape(txt)

    /.../local/lib/python2.7/site-packages/newspaper/parsers.pyc in getText(cls, node)
        194     @classmethod
        195     def getText(cls, node):
    --> 196         txts = [i for i in node.itertext()]
        197         return text.innerTrim(u' '.join(txts).strip())
        198 

    /.../local/lib/python2.7/site-packages/lxml/etree.so in lxml.etree._Element.itertext (src/lxml/lxml.etree.c:51098)()

    /.../local/lib/python2.7/site-packages/lxml/etree.so in lxml.etree.ElementTextIterator.__cinit__ (src/lxml/lxml.etree.c:68059)()

    /.../local/lib/python2.7/site-packages/lxml/etree.so in lxml.etree.iterwalk.__init__ (src/lxml/lxml.etree.c:131973)()

    /.../local/lib/python2.7/site-packages/lxml/etree.so in lxml.etree._rootNodeOrRaise (src/lxml/lxml.etree.c:14641)()

    ValueError: Input object has no element: HtmlProcessingInstruction

**Comment by yprez** [comment]
The node it fails on is: `<?EM-dummyText [Tagline] ?>`, when calling `node.itertext()`:
```
ipdb> node
<?EM-dummyText [Tagline] ?>

ipdb> node.itertext()
*** ValueError: Input object has no element: HtmlProcessingInstruction
```

**Comment by codelucas** [comment]
See my comment on #144

**Comment by codelucas** [comment]
This is fixed

**Comment by chenleishen** [comment]
I'm still getting error with these links for some reason: http://feedproxy.google.com/~r/businessinsider/~3/pRrDU5xaDZE/mitt-romney-reportedly-considering-running-for-utah-senate-seat-2017-4
http://feedproxy.google.com/~r/businessinsider/~3/B835PMAH09Q/afp-uruguay-to-sell-marijuana-in-pharmacies-from-july-2017-4
http://feedproxy.google.com/~r/businessinsider/~3/Fj6OXtF_fj0/justice-department-task-force-will-review-weed-enforcement-policy-2017-4

**Comment by chenleishen** [comment]
nvm, upgraded project to Python3 and is currently using newspaper3k
