### ISSUE TITLE
Icon Image ValueError difficult to interpret

### ISSUE THREAD

**Issue by adamn** [codelucas/newspaper#252]
Pillow is raising a ValueError and Newspaper is printing it.  It should instead be raised for the exception handler on images:153 so the user knows what's happening (i.e. what url failed, etc..).

```python
Traceback (most recent call last):
 File "/var/virtualenvs/centr/lib/python3.5/site-packages/newspaper/images.py", line 121, in fetch_url
   p.feed(new_data)
 File "/var/virtualenvs/centr/lib/python3.5/site-packages/PIL/ImageFile.py", line 377, in feed
   im = Image.open(fp)
 File "/var/virtualenvs/centr/lib/python3.5/site-packages/PIL/Image.py", line 2299, in open
   im = _open_core(fp, filename, prefix)
 File "/var/virtualenvs/centr/lib/python3.5/site-packages/PIL/Image.py", line 2289, in _open_core
   im = factory(fp, filename)
 File "/var/virtualenvs/centr/lib/python3.5/site-packages/PIL/ImageFile.py", line 97, in __init__
   self._open()
 File "/var/virtualenvs/centr/lib/python3.5/site-packages/PIL/IcoImagePlugin.py", line 264, in _open
   self.load()
 File "/var/virtualenvs/centr/lib/python3.5/site-packages/PIL/IcoImagePlugin.py", line 267, in load
   im = self.ico.getimage(self.size)
 File "/var/virtualenvs/centr/lib/python3.5/site-packages/PIL/IcoImagePlugin.py", line 150, in getimage
   return self.frame(i)
 File "/var/virtualenvs/centr/lib/python3.5/site-packages/PIL/IcoImagePlugin.py", line 201, in frame
   ('L', 0, -1)    # 8bpp inverted, unpadded, reversed
 File "/var/virtualenvs/centr/lib/python3.5/site-packages/PIL/Image.py", line 2131, in frombuffer
   core.map_buffer(data, size, decoder_name, None, 0, args)
ValueError: buffer is not large enough
```

**Comment by yprez** [comment]
@adamn,  I don't think I've seen this one before... do you have an example URL where it happens?

**Comment by adamn** [comment]
Yes I do. https://pypi.python.org/pypi/GraphLab-Create/1.10.1

**Comment by adamn** [comment]
This is broken in 0.1.7 but is now fixed :-)

So, no worries.

**Comment by Myosotis** [comment]
Hello! I have another example URL where it still happens https://yandex.st/lego/_/Gkmfl8ZxooHEnbHJEo5KoZ0AVP0.ico

```
Traceback (most recent call last):
  File "D:\Project\Part 2\ex.py", line 58, in get_image_size
    p.feed(data)
  File "C:\Users\Myosotis\AppData\Local\Programs\Python\Python35-32\lib\site-packages\PIL\ImageFile.py", line 383, in feed
    im = Image.open(fp)
  File "C:\Users\Myosotis\AppData\Local\Programs\Python\Python35-32\lib\site-packages\PIL\Image.py", line 2309, in open
    im = _open_core(fp, filename, prefix)
  File "C:\Users\Myosotis\AppData\Local\Programs\Python\Python35-32\lib\site-packages\PIL\Image.py", line 2299, in _open_core
    im = factory(fp, filename)
  File "C:\Users\Myosotis\AppData\Local\Programs\Python\Python35-32\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Users\Myosotis\AppData\Local\Programs\Python\Python35-32\lib\site-packages\PIL\IcoImagePlugin.py", line 264, in _open
    self.load()
  File "C:\Users\Myosotis\AppData\Local\Programs\Python\Python35-32\lib\site-packages\PIL\IcoImagePlugin.py", line 267, in load
    im = self.ico.getimage(self.size)
  File "C:\Users\Myosotis\AppData\Local\Programs\Python\Python35-32\lib\site-packages\PIL\IcoImagePlugin.py", line 150, in getimage
    return self.frame(i)
  File "C:\Users\Myosotis\AppData\Local\Programs\Python\Python35-32\lib\site-packages\PIL\IcoImagePlugin.py", line 201, in frame
    ('L', 0, -1)    # 8bpp inverted, unpadded, reversed
  File "C:\Users\Myosotis\AppData\Local\Programs\Python\Python35-32\lib\site-packages\PIL\Image.py", line 2132, in frombuffer
    core.map_buffer(data, size, decoder_name, None, 0, args)
ValueError: buffer is not large enough
```

**Comment by saattrupdan** [comment]
I came across another one where this happens. I'm afraid I don't have the exact link, as this was part of parsing ~10k articles, but this is my traceback:
```python
Traceback (most recent call last):
  File "/Users/saattrupdan/.venv/lib/python3.8/site-packages/newspaper/images.py", line 118, in fetch_url
    p.feed(new_data)
  File "/Users/saattrupdan/.venv/lib/python3.8/site-packages/PIL/ImageFile.py", line 415, in feed
    im = Image.open(fp)
  File "/Users/saattrupdan/.venv/lib/python3.8/site-packages/PIL/Image.py", line 3009, in open
    im = _open_core(fp, filename, prefix, formats)
  File "/Users/saattrupdan/.venv/lib/python3.8/site-packages/PIL/Image.py", line 2995, in _open_core
    im = factory(fp, filename)
  File "/Users/saattrupdan/.venv/lib/python3.8/site-packages/PIL/ImageFile.py", line 121, in __init__
    self._open()
  File "/Users/saattrupdan/.venv/lib/python3.8/site-packages/PIL/IcoImagePlugin.py", line 294, in _open
    self.load()
  File "/Users/saattrupdan/.venv/lib/python3.8/site-packages/PIL/IcoImagePlugin.py", line 310, in load
    im = self.ico.getimage(self.size)
  File "/Users/saattrupdan/.venv/lib/python3.8/site-packages/PIL/IcoImagePlugin.py", line 180, in getimage
    return self.frame(self.getentryindex(size, bpp))
  File "/Users/saattrupdan/.venv/lib/python3.8/site-packages/PIL/IcoImagePlugin.py", line 221, in frame
    mask = Image.frombuffer(
  File "/Users/saattrupdan/.venv/lib/python3.8/site-packages/PIL/Image.py", line 2785, in frombuffer
    im = im._new(core.map_buffer(data, size, decoder_name, 0, args))
ValueError: buffer is not large enough
```

I noticed in `images.py` that this is simply (as mentioned in the comments above) that the `ValueError` is printed. It concerns [line 117-126 in images.py](https://github.com/codelucas/newspaper/blob/f622011177f6c2e95e48d6076561e21c016f08c3/newspaper/images.py#L117-L126):
```python
try:
    p.feed(new_data)
except IOError:
    traceback.print_exc()
    p = None
    break
except ValueError:
    traceback.print_exc()
    p = None
    break
```

Unless I'm mistaken, shouldn't the `traceback.print_exc()` lines either be replaced by a `raise`, or alternatively include an argument in the `Article` constructor akin to `print_errors: bool = False`?
